### ISSUE TITLE
Can't start project

### ISSUE THREAD

**Issue by ariran5** [mediamanDE/three-sixty#16]
Hi, I like your plugin and I have plans for improvements, but I can not run the project. Please reduce the number of dependencies

**Comment by R4c00n** [comment]
Hello @ariran5, could you please provide a bit more information what's not working out for you?

**Comment by ariran5** [comment]
Mac 13.4
nodes 10.1.0-10.4.0
npm 5.6 - 6.1

I can't install lib-sass and fsevents, node-gyp error
```

MBP-Arian:three-sixty$ npm i

> fsevents@1.1.2 install /Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.4.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.4.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.ccIn file included from :../fsevents.cc6::
6In file included from :
../../nan/nan.hIn file included from ../../nan/nan.h::192192:
:
../../nan/nan_maybe_43_inl.h:112:15: error: ../../nan/nan_maybe_43_inl.h:112:15: error: nono member named 'ForceSet' member named 'ForceSet' in
      'v8::Object' 
in
      'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18:In file included from  ../fsevents.cc:6:
../../nan/nan.h:834warning:: 18: 'MakeCallback' iswarning : deprecated: Use'MakeCallback'
       isMakeCallback(...,  deprecated:async_context)  Use[-Wdeprecated-declarations]
      
MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
    return node::MakeCallback(
                 ^
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h:171:/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h1::171 :1:note : 
note      : 'MakeCallback' 
has       'MakeCallback'been  hasexplicitly  beenmarked  explicitlydeprecated  markedhere deprecated
 here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h:88:20: note: /Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h:expanded88
:      20from:  macro 'NODE_DEPRECATED'note: 
expanded
      from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h../../nan/nan.h::849849::1818::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse

            MakeCallback(...,MakeCallback(...,  async_context)async_context)  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return node::MakeCallback(    return node::MakeCallback(

                 ^                 ^

/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h::164164::11::  notenote: : 
      
'MakeCallback'      'MakeCallback' has been  explicitly hasmarked  beendeprecated  explicitlyhere marked
 deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h:88:20:/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h :88:note20: : expanded
      notefrom:  macroexpanded 
'NODE_DEPRECATED'      from
 macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h../fsevents.cc::8646::
18: ../../nan/nan.h:864warning:: 18: 'MakeCallback' iswarning : deprecated: Use'MakeCallback'
       isMakeCallback(...,  deprecated:async_context)  Use[-Wdeprecated-declarations]
      
MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
    return node::MakeCallback(
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h                 ^:
157:1: /Users/ariansapiro/.node-gyp/10.4.0/include/node/node.hnote:: 157:
1      :'MakeCallback'  has notebeen:  explicitly 
marked       'MakeCallback'deprecated  hashere been
 explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.hNODE_DEPRECATED("Use MakeCallback(..., async_context)",:
88:20^:
 note: /Users/ariansapiro/.node-gyp/10.4.0/include/node/node.hexpanded:
88      :from20 :macro  'NODE_DEPRECATED'note
: expanded
      from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h:171:1: note: 
      'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h:88:20: note: expanded
      from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h:171:1: note: 
      'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/ariansapiro/.node-gyp/10.4.0/include/node/node.h:88:20: note: expanded
      from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
4 warnings and 1 error generated.
make: make: *** [Release/obj.target/fse/fsevents.o] Error 1
*** [Release/obj.target/fse/fsevents.o] Error 1
gypgyp  ERR! build errorERR! 
 build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp gypERR! stack      at ChildProcess.onExit (/Users/ariansapiro/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gypERR!  ERR!stack  Error: `make` failed with exit code: 2
stack     at ChildProcess.emit (events.js:182:13)
gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
     at ChildProcess.onExit (/Users/ariansapiro/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp gyp ERR! ERR!stack      at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
System Darwin 17.5.0
gyp ERR! commandgyp "/Users/ariansapiro/.nvm/versions/node/v10.4.0/bin/node" "/Users/ariansapiro/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
 ERR!gyp  System Darwin 17.5.0
ERR! cwd /Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents
gypgyp  ERR! ERR!command  "/Users/ariansapiro/.nvm/versions/node/v10.4.0/bin/node" "/Users/ariansapiro/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
node -v v10.4.0
gypgyp  ERR!ERR!  cwd /Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents
node-gyp -v v3.6.2
gyp ERR!gyp  node -v v10.4.0
ERR!gyp  ERR! not oknode-gyp -v 
 v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ariansapiro/.nvm/versions/node/v10.4.0/bin/node /Users/ariansapiro/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/Users/ariansapiro/.nvm/versions/node/v10.4.0/bin/node" "/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents
node-pre-gyp ERR! node -v v10.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/Users/ariansapiro/.nvm/versions/node/v10.4.0/bin/node /Users/ariansapiro/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/ariansapiro/Desktop/three-sixty/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
npm WARN rollup-plugin-typescript2@0.9.0 requires a peer of rollup@^0.50.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 11498 packages in 12.949s
found 306 vulnerabilities (219 low, 67 moderate, 20 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by R4c00n** [comment]
Hello @ariran5,
it seems like your xcode is not installed/configured correctly. Please try the solutions from the official node-gyp project: https://github.com/nodejs/node-gyp/issues/569

Please let me know if this fixes your problem.

**Comment by ariran5** [comment]
I've reinstalled xcode several times, it doesn't help.

**Comment by ariran5** [comment]
I removed all dependencies and write on pure js , I do the progress bars, events and fix some errors, are you interested in such a pull request ?

**Comment by R4c00n** [comment]
Hello @ariran5,
the node-sass library version we use is, indeed, not working on node >= 10. But the error message should be a different one than the one in your logs. 
Can you please check out branch `bugfix/update-node-sass-version` and do a fresh `npm install` run? Tested it successfully on MacOS 10.12.6 with Node 10.4.0 and npm 6.1.0.

**Comment by R4c00n** [comment]
Closing this issue because of no activity for a while. @ariran5 Please reopen this issue if the problem still occurs for you with the latest version.
